name: CI

on:
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.version.outputs.sha }}
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: 'Compute version string'
        id: version
        run: |
          SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAG=0-ea
          VERSION=${TAG}+${SHA}
          echo "::set-output name=sha::${SHA}"
          echo "::set-output name=tag::${TAG}"
          echo "::set-output name=version::${VERSION}"

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up Java'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea
      - name: 'Cache bucket'
        uses: actions/cache@v2
        with:
          path: bucket
          key: bucket
      - name: 'Sync bucket'
        run: |
          mkdir --parents bucket
          du --bytes bucket
          aws s3 sync s3://java9plusadoption bucket --region us-east-1 --no-sign-request --only-show-errors
          du --bytes bucket
      - name: 'Scan bucket'
        run: |
          java \
          com.github.sormuras.modules/com/github/sormuras/modules/Scanner.java \
          bucket \
          com.github.sormuras.modules/com/github/sormuras/modules/modules.properties
      - name: 'Build with Bach'
        uses: sormuras/bach-build@v1
        with:
          bach-version: 17-ea
          project-version: ${{ needs.setup.outputs.version }}
      - name: 'Upload artifact ${{ github.event.repository.name }}-build-${{ needs.setup.outputs.version }}'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ needs.setup.outputs.version }}
          path: |
            LICENSE
            .bach/workspace/logbook.md
            .bach/workspace/modules
      - name: 'Check for modifications'
        id: diff
        run: |
          git status
          echo ::set-output name=modified::$(if [[ -z $(git status --porcelain) ]]; then echo 'false'; else echo 'true'; fi)
      - name: 'Commit and push changes'
        if: steps.diff.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --message 'Update ${{ github.event.repository.name }} to ${{ needs.setup.outputs.version }}'
          git push

  deploy-to-releases:
    needs: [ setup, build ]
    if: github.repository == 'sormuras/modules' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download build artifact ${{ needs.setup.outputs.version }}'
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ needs.setup.outputs.version }}
      - name: 'Release ${{ needs.setup.outputs.tag }}'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: ${{ needs.setup.outputs.tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "Modules ${{ needs.setup.outputs.version }}"
          files: |
            .bach/workspace/modules/*.jar
            com.github.sormuras.modules/com/github/sormuras/modules/modules.properties
